mitmproxy 9.0.1 API fixes
This also fixes the following error with HTTP flows introduced in 22b80fa6:
AttributeError: 'HTTPFlow' object has no attribute 'context'